import { lazy } from 'react';
import './party.css';

// Add a new game: create the component, then add one entry here.
export const GAMES = [
  {
    id: 'bomb',
    title: 'Hot potato bomb',
    emoji: '💣',
    blurb: 'Name something in the category, pass the bomb. Secret fuse. Whoever’s holding it does a forfeit.',
    tag: 'Chaos',
    isNew: true,
    Component: lazy(() => import('./Bomb.jsx')),
  },
  {
    id: 'duel',
    title: 'Quickdraw duel',
    emoji: '🤠',
    blurb: 'Wait for it… DRAW! Fastest reaction wins. Shoot early and you lose the round.',
    tag: 'Reflex',
    isNew: true,
    Component: lazy(() => import('./Duel.jsx')),
  },
  {
    id: 'booth',
    title: 'Photo booth',
    emoji: '📸',
    blurb: 'Silly prompts, a 3-2-1 countdown, both cameras snap at once. Download your strip together.',
    tag: 'Keepsake',
    isNew: true,
    Component: lazy(() => import('./PhotoBooth.jsx')),
  },
  {
    id: 'meld',
    title: 'Mind meld',
    emoji: '🧠',
    blurb: 'Type a word at the same time. Different? Find the word that links them. Repeat until you match.',
    tag: 'Telepathy',
    isNew: true,
    Component: lazy(() => import('./MindMeld.jsx')),
  },
  {
    id: 'wave',
    title: 'Same wavelength',
    emoji: '📡',
    blurb: 'One sees a secret spot on a dial and gives a clue. The other moves the needle to find it.',
    tag: 'Co-op',
    isNew: true,
    Component: lazy(() => import('./Wavelength.jsx')),
  },
  {
    id: 'clock',
    title: 'Inner clock',
    emoji: '⏱️',
    blurb: 'Count seconds in your head with no timer. Closest wins, and stopping together means you’re in sync.',
    tag: 'Quick',
    isNew: true,
    Component: lazy(() => import('./InnerClock.jsx')),
  },
  {
    id: 'puzzle',
    title: 'Photo puzzle',
    emoji: '🧩',
    blurb: 'Turn one of your photos into a puzzle. Solve it together or race to finish first.',
    tag: 'Co-op or race',
    Component: lazy(() => import('./Puzzle.jsx')),
  },
  {
    id: 'movie',
    title: 'Movie night',
    emoji: '🍿',
    blurb: 'One of you shares a tab or window and you watch together. The call floats on top.',
    tag: 'Watch together',
    Component: lazy(() => import('./MovieNight.jsx')),
  },
  {
    id: 'racing',
    title: 'Sweetheart Speedway',
    emoji: '🏎️',
    blurb: 'Pick a track, a car and a driver, then race each other for three laps.',
    tag: 'Race',
    Component: lazy(() => import('./racing/Racing.jsx')),
  },
  {
    id: 'tod',
    title: 'Truth or dare',
    emoji: '🍻',
    blurb: 'Sweet, spicy or wild cards, plus Never Have I Ever. Turn on drinking rules if you dare.',
    tag: 'Party',
    Component: lazy(() => import('./TruthOrDare.jsx')),
  },
  {
    id: 'draw',
    title: 'Draw & guess',
    emoji: '🎨',
    blurb: 'One draws, the other guesses before the timer runs out. Swap every round.',
    tag: 'Co-op',
    Component: lazy(() => import('./DrawGuess.jsx')),
  },
  {
    id: 'wyr',
    title: 'Would you rather',
    emoji: '🤔',
    blurb: 'Both answer in secret, then reveal. See how often you think alike.',
    tag: 'Chat',
    Component: lazy(() => import('./WouldYouRather.jsx')),
  },
  {
    id: 'c4',
    title: 'Connect four',
    emoji: '🔴',
    blurb: 'Drop discs, get four in a row. Quick rounds, best for settling arguments.',
    tag: 'Versus',
    Component: lazy(() => import('./ConnectFour.jsx')),
  },
];
